title: Nikola Bozhinov
description: "e-learning developer from Bulgaria"
baseurl: ""
url: "https://vislupus.github.io/"
github_username: vislupus
linkedin: nikolabozhinov
email: nikolaobozhinov@gmail.com


# Build settings
markdown: kramdown
kramdown:
    math_engine: katex
sass:
    style: :compressed
plugins:
  - jekyll-feed